@if(\Auth::guard('admin')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-admin')
@endif
@if(\Auth::guard('reception_employee')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-reception_employee')
@endif
@if(\Auth::guard('patient')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-patient')
@endif
@if(\Auth::guard('doctor')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-doctor')
@endif
@if(\Auth::guard('ray_employee')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-ray_employee')
@endif
@if(\Auth::guard('laboratory_employee')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-laboratory_employee')
@endif
@if(\Auth::guard('accounting_employee')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-accounting_employee')
@endif
@if(\Auth::guard('pharmacy_employee')->check())
@include('Dashboard.layouts.main-sidebar.main-sidebar-Pharmacy_employee')
@endif
